name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
       image: rocm/dev-ubuntu-22.04:6.3
    steps:
      - name: Install baseline OS dependencies
        run: |
          sudo apt-get update	
          sudo apt-get install -y cmake
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set ROCm path
        run: |
          echo "/opt/rocm/bin" >> $GITHUB_PATH      
      - name: Configure and install
        run: |
          mkdir build
          cd build
          cmake ..
          make install
      - name: Confirm install binary
        run: |
          test -x /opt/rocm/bin/roofline

